language: python

os: linux
dist: focal

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'

# commands to install dependencies
install:
  - "pip install flake8 pytest-cov pytest coveralls"
  - "pip install -r requirements.txt"

# commands to run tests
script:
  - "flake8 checkdmarc_signalless.py"
  - "flake8 tests.py"
  - "cd docs"
  - "make html"
  - "cd .."
  - "python tests.py"
  - "coverage run tests.py"
  - "python setup.py sdist"
  - "python setup.py bdist_wheel"

after_success:
  - "codecov"
